_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "detco_AA.pkl"
  BACKBONE:
    FREEZE_AT: 0
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
    NORM: "SyncBN"
  SparseRCNN:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:
  PRECISE_BN:
    ENABLED: True