_BASE_: "Base-SparseRCNN.yaml"
MODEL:
  WEIGHTS: "./pretrained/dgmn2_small.pth"
  BACKBONE:
    NAME: "build_dgmn2_fpn_backbone"
    SCALE: "small"
  RESNETS:
    DEPTH: 50
    STRIDE_IN_1X1: False
  SparseRCNN:
    NUM_PROPOSALS: 300
    NUM_CLASSES: 80
DATASETS:
  TRAIN: ("coco_2017_train",)
  TEST:  ("coco_2017_val",)
SOLVER:
  STEPS: (210000, 250000)
  MAX_ITER: 270000
INPUT:
  CROP:
    ENABLED: True
  FORMAT: "RGB"
TEST:
  EVAL_PERIOD: 5000
OUTPUT_DIR: "./output/SparseRCNN_DGMN2_small"
